# Name of workflow
name: Hello World

# Trigger the workflow on push or pull request
on:
  - push

jobs:
  build:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: print Hello World

      - run: make say-hello